apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-services
spec:
  replicas: 1
  selector:
    matchLabels:
      name: managed-services
  template:
    metadata:
      labels:
        name: managed-services
    spec:
      containers:
        - name: managed-services
          image: maleck13/managed-services-operator
          command:
          - managed-services
          imagePullPolicy: Always
