apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sharedserviceclients.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: SharedServiceClient
    listKind: SharedServiceClientList
    plural: sharedserviceclients
    singular: sharedserviceclient
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clientType:
              type: string