apiVersion: "aerogear.org/v1alpha1"
kind: "SharedService"
metadata:
  name: "example"
spec:
  image: "docker.io/aerogearcatalog/keycloak-apb:1.0.0-alpha"
  cluster_service_class_external_name: "dh-keycloak-apb"
  params: 
    ADMIN_USERNAME: "admin"
    ADMIN_PASSWORD: "admin"
    USE_SHARED_SERVICE: false
