apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sharedserviceslices.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: SharedServiceSlice
    listKind: SharedServiceSliceList
    plural: sharedserviceslices
    singular: sharedserviceslice
  scope: Namespaced
  version: v1alpha1
  validation:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              serviceType:
                type: string
              params:
                description: parameteres for creating the slices
                type: object
