apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sharedservices.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: SharedService
    listKind: SharedServiceList
    plural: sharedservices
    singular: sharedservice
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            service:
              type: string
            minimumInstances:
              type: int
            maximumInstances:
              type: int
            currentInstances:
              type: object
            requestedInstances:
              type: int
            params:
              description: parameters for creating the services
              type: object
            slicesPerInstance:
              type: int