apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sharedserviceinstances.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: SharedServiceInstance
    listKind: SharedServiceInstanceList
    plural: sharedserviceinstances
    singular: sharedserviceinstance
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            service:
              type: string
            image:
              type: string
            clusterServiceClassExternalName:
              type: string
            clusterServiceClassName:
              type: string
            params:
              description: parameteres for creating the service
              type: object
            serviceInstance:
              type: string
            maxSlices:
              type: int
            currentSlices:
              type: object  
          